name: Workflow test
on: [push]
jobs:
  python_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - name: Check python version
        run: python --version

  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python
        uses: actions/setup-python@v4
      - name: Requirements
        run: py -m pip install -r requirements.txt
      - name: Pylint
        run: py -m pip install pylint
      - name: Test
        run: py -m pylint app.py